POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "blog",
    "author": "lh",
    "url": "www.com",
    "likes": 10
}

###

DELETE http://localhost:3003/api/blogs/629f204b8e137cda0de88f91

###

GET http://localhost:3003/api/blogs